swagger: '2.0'
info:
  title: TeamDynamix Wrapper API
  description: Wrapper API for TeamDynamix to perform some data manipulation.
  version: '1.0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/td-wrapper-api
host: localhost
schemes:
  - https
basePath: /v1
produces:
  - application/json
consumes:
  - application/json
paths:
  /teamdynamix/services:
    get:
      summary: Get all services
      description: Get all services with their long descriptions.
      parameters:
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/ServicesResultObject'
  /teamdynamix/services/{id}:
    get:
      summary: Get a single service by its ID
      description: Get a single service by its ID.
      parameters:
        - $ref: '#/parameters/pretty'
        - $ref: '#/parameters/id'
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/ServiceResultObject'
        404:
          description: Service with the specific ID not found.
          schema:
            $ref: '#/definitions/Errors'
parameters:
  id:
    name: id
    in: path
    required: true
    description: Unique ID of TD service
    type: string
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed
definitions:
  ServicesResultObject:
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/ServiceResourceObject"
  ServiceResultObject:
    properties:
      data:
        properties:
          id:
            type: string
            description: service ID.
          type:
            type: string
            description: service
          links:
            $ref: "#/definitions/NullSelfLink"
          attributes:
            $ref: "#/definitions/ServiceResourceObject"
  ServiceResourceObject:
    properties:
      attachments:
        type: array
        description: service attachments.
        items:
          $ref: "#/definitions/Attachment"
      categoriesParsedFromFullCategoryText:
        type: string
        description: categoriesParsedFromFullCategoryText
      categoryID:
        type: string
        description: ID of the containing category.
      categoryName:
        type: string
        description: name of the containing category.
      compositeName:
        type: string
        description: composite name of the service, which includes the name of the immediate parent category.
      configurationItemID:
        type: string
        description: ID of the associated configuration item record.
      fullCategoryText:
        type: string
        description: full text of the category hierarchy.
      isActive:
        type: boolean
        description: a boolean value indicating whether the service is active.
      isPublic:
        type: boolean
        description: a boolean value indicating whether the service is public; that is, if it is visible to unauthenticated users.
      longDescription:
        type: string
        description: service's long description, which is used when viewing the specific service. This can contain HTML.
      maintenanceScheduleID:
        type: string
        description: ID of the associated maintenance window.
      maintenanceScheduleName:
        type: string
        description: name of the associated maintenance window.
      managerFullName:
        type: string
        description: full name of the managing person.
      managerUid:
        type: string
        description: UID of the managing person.
      managingGroupID:
        type: string
        description: ID of the managing group.
      managingGroupName:
        type: string
        description: name of the managing group.
      name:
        type: string
        description: service name.
      newTicketUrl:
        type: string
        description: new ticket URL
      order:
        type: string
        description: order of the service among its siblings.
      requestApplicationID:
        type: string
        description: ID of the destination application for any generated requests.
      requestApplicationIsActive:
        type: boolean
        description: active status of the destination application for any generated requests.
      requestApplicationName:
        type: string
        description: name of the destination application for any generated requests.
      requestText:
        type: string
        description: custom text used for the "Request This" button.
      requestTypeCategoryID:
        type: string
        description: ID of the associated request type's containing category.
      requestTypeCategoryName:
        type: string
        description: name of the associated request type's containing category.
      requestTypeComponent:
        type: integer
        enum: [0, 1, 4, 9]
        description: >
          Sort oder:
            * 0  - [None] Indicates that a service is not tied to any particular kind of request.
            * 1  - [Project] Indicates that a service is tied to some type of project request.
            * 4  - [Link] Indicates that a service is tied to an external request available at a custom URL.
            * 9  - [Ticket] Indicates that a service is tied to some sort of ticket request.
      requestTypeID:
        type: string
        description: ID of the associated request type.
      requestTypeIsActive:
        type: boolean
        description: a boolean value indicating whether the associated request type is active.
      requestTypeName:
        type: string
        description: name of the associated request type.
      requestUrl:
        type: string
        description: custom request URL configured for this service.
      shortDescription:
        type: string
        description: service's short description, which is used when displaying the service in a list
      spanTagsParsedFromLongDescription:
        type: object
        description: span HTML tags in the long description
        properties:
          accessRequirements:
            type: string
            description: access requirements
          additionalLinkTitle:
            type: string
            description: additional link title
          additionalLinkURL:
            type: string
            description: additional link URL
          audienceAssociated:
            type: string
            description: audience associated
          audienceDepartments:
            type: string
            description: audience departments
          audienceDescription:
            type: string
            description: audience description
          audienceEmployees:
            type: string
            description: audience employees
          audienceStudents:
            type: string
            description: audience students
          businessContact:
            type: string
            description: business contact
          businessImpact:
            type: string
            description: business impact
          businessOwner:
            type: string
            description: business owner
          businessPriority:
            type: string
            description: business priority
          businessUnit:
            type: string
            description: business unit
          chargesOptionsFees:
            type: string
            description: charges options fees
          cost:
            type: string
            description: cost
          enablingServices:
            type: string
            description: enabling services
          enhancingServices:
            type: string
            description: enhancing services
          escalationContact:
            type: string
            description: escalation contact
          losLearn:
            type: string
            description: LOS learn
          losOperate:
            type: string
            description: LOS Operate
          losResearch:
            type: string
            description: LOS research
          losWork:
            type: string
            description: LOS work
          longDescription:
            type: string
            description: long description
          relatedServices:
            type: string
            description: related services
          requestAccess:
            type: string
            description: request access
          sla:
            type: string
            description: SLA
          securityRating:
            type: string
            description: security rating
          serviceHours:
            type: string
            description: service hours
          serviceManager:
            type: string
            description: service manager
          serviceOwner:
            type: string
            description: service owner
          serviceType:
            type: string
            description: service type
          shortDescription:
            type: string
            description: short description
          supportAvailability:
            type: string
            description: support availability
          synonymsList:
            type: array
            description: synonyms list
            items:
              type: string
          training:
            type: string
            description: training
          value:
            type: string
            description: value
  Attachment:
    properties:
      id:
        type: string
        description: attachment ID.
      attachmentType:
        type: integer
        enum: [0, 1, 3, 7, 9, 11, 13, 14, 26, 27, 29, 63]
        description: >
          Sort oder:
            * 0  - [None] Indicates that the type of attachment is unknown.
            * 1  - [Project] A project attachment.
            * 3  - [Issue] An issue attachment.
            * 7  - [Announcement] An announcement attachment.
            * 9  - [Ticket] A ticket attachment.
            * 11 - [Opportunity] An opportunity attachment.
            * 13 - [Forums] A forum post attachment.
            * 14 - [Account] A CRM account attachment.
            * 26 - [KnowledgeBase] A Knowledge Base article attachment.
            * 27 - [Asset] An asset attachment.
            * 29 - [Contract] An asset contract attachment.
            * 63 - [ConfigurationItem] A configuration item attachment.
      itemID:
        type: string
        description: item ID.
      createdUid:
        type: string
        description: UID of the creator.
      createdFullName:
        type: string
        description: full name of the creator.
      createdDate:
        type: string
        description: creation date.
      name:
        type: string
        description: file name.
      size:
        type: integer
        description: size of the attachment, in bytes.
      uri:
        type: string
        description: URI for this attachment.
      contentUri:
        type: string
        description: URI to retrieve the attachment content.
  NullSelfLink:
    properties:
      self:
        type: string
        format: url
        description: Self link for resource object, currently null.
        example: null
  Errors:
    type: array
    items:
      $ref: "#/definitions/Error"
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
